import { EnumType } from './types';

export const cities: EnumType[] = [
  { code: '001', value: 'Adamantina' },
  { code: '002', value: 'Adolfo' },
  { code: '003', value: 'Aguaí' },
  { code: '004', value: 'Águas da Prata' },
  { code: '005', value: 'Águas de Lindóia' },
  { code: '006', value: 'Águas de Santa Bárbara' },
  { code: '007', value: 'Águas de São Pedro' },
  { code: '008', value: 'Agudos' },
  { code: '009', value: 'Alambari' },
  { code: '010', value: 'Alfredo Marcondes' },
  { code: '011', value: 'Altair' },
  { code: '012', value: 'Altinópolis' },
  { code: '013', value: 'Alto Alegre' },
  { code: '014', value: 'Alumínio' },
  { code: '015', value: 'Álvares Florence' },
  { code: '016', value: 'Álvares Machado' },
  { code: '017', value: 'Álvaro de Carvalho' },
  { code: '018', value: 'Alvinlândia' },
  { code: '019', value: 'Americana' },
  { code: '020', value: 'Américo Brasiliense' },
  { code: '021', value: 'Américo de Campos' },
  { code: '022', value: 'Amparo' },
  { code: '023', value: 'Analândia' },
  { code: '024', value: 'Andradina' },
  { code: '025', value: 'Angatuba' },
  { code: '026', value: 'Anhembi' },
  { code: '027', value: 'Anhumas' },
  { code: '028', value: 'Aparecida' },
  { code: '029', value: "Aparecida d'Oeste" },
  { code: '030', value: 'Apiaí' },
  { code: '031', value: 'Araçariguama' },
  { code: '032', value: 'Araçatuba' },
  { code: '033', value: 'Araçoiaba da Serra' },
  { code: '034', value: 'Aramina' },
  { code: '035', value: 'Arandu' },
  { code: '036', value: 'Arapeí' },
  { code: '037', value: 'Araraquara' },
  { code: '038', value: 'Araras' },
  { code: '039', value: 'Arco-Íris' },
  { code: '040', value: 'Arealva' },
  { code: '041', value: 'Areias' },
  { code: '042', value: 'Areiópolis' },
  { code: '043', value: 'Ariranha' },
  { code: '044', value: 'Artur Nogueira' },
  { code: '045', value: 'Arujá' },
  { code: '046', value: 'Aspásia' },
  { code: '047', value: 'Assis' },
  { code: '048', value: 'Atibaia' },
  { code: '049', value: 'Auriflama' },
  { code: '050', value: 'Avaí' },
  { code: '051', value: 'Avanhandava' },
  { code: '052', value: 'Avaré' },
  { code: '053', value: 'Bady Bassitt' },
  { code: '054', value: 'Balbinos' },
  { code: '055', value: 'Bálsamo' },
  { code: '056', value: 'Bananal' },
  { code: '057', value: 'Barão de Antonina' },
  { code: '058', value: 'Barbosa' },
  { code: '059', value: 'Bariri' },
  { code: '060', value: 'Barra Bonita' },
  { code: '061', value: 'Barra do Chapéu' },
  { code: '062', value: 'Barra do Turvo' },
  { code: '063', value: 'Barretos' },
  { code: '064', value: 'Barrinha' },
  { code: '065', value: 'Barueri' },
  { code: '066', value: 'Bastos' },
  { code: '067', value: 'Batatais' },
  { code: '068', value: 'Bauru' },
  { code: '069', value: 'Bebedouro' },
  { code: '070', value: 'Bento de Abreu' },
  { code: '071', value: 'Bernardino de Campos' },
  { code: '072', value: 'Bertioga' },
  { code: '073', value: 'Bilac' },
  { code: '074', value: 'Birigui' },
  { code: '075', value: 'Biritiba-Mirim' },
  { code: '076', value: 'Boa Esperança do Sul' },
  { code: '077', value: 'Bocaina' },
  { code: '078', value: 'Bofete' },
  { code: '079', value: 'Boituva' },
  { code: '080', value: 'Bom Jesus dos Perdões' },
  { code: '081', value: 'Bom Sucesso de Itararé' },
  { code: '082', value: 'Borá' },
  { code: '083', value: 'Boracéia' },
  { code: '084', value: 'Borborema' },
  { code: '085', value: 'Borebi' },
  { code: '086', value: 'Botucatu' },
  { code: '087', value: 'Bragança Paulista' },
  { code: '088', value: 'Braúna' },
  { code: '089', value: 'Brejo Alegre' },
  { code: '090', value: 'Brodowski' },
  { code: '091', value: 'Brotas' },
  { code: '092', value: 'Buri' },
  { code: '093', value: 'Buritama' },
  { code: '094', value: 'Buritizal' },
  { code: '095', value: 'Cabrália Paulista' },
  { code: '096', value: 'Cabreúva' },
  { code: '097', value: 'Caçapava' },
  { code: '098', value: 'Cachoeira Paulista' },
  { code: '099', value: 'Caconde' },
  { code: '100', value: 'Cafelândia' },
  { code: '101', value: 'Caiabu' },
  { code: '102', value: 'Caieiras' },
  { code: '103', value: 'Caiuá' },
  { code: '104', value: 'Cajamar' },
  { code: '105', value: 'Cajati' },
  { code: '106', value: 'Cajobi' },
  { code: '107', value: 'Cajuru' },
  { code: '108', value: 'Campina do Monte Alegre' },
  { code: '109', value: 'Campinas' },
  { code: '110', value: 'Campo Limpo Paulista' },
  { code: '111', value: 'Campos do Jordão' },
  { code: '112', value: 'Campos Novos Paulista' },
  { code: '113', value: 'Cananéia' },
  { code: '114', value: 'Canas' },
  { code: '115', value: 'Cândido Mota' },
  { code: '116', value: 'Cândido Rodrigues' },
  { code: '117', value: 'Canitar' },
  { code: '118', value: 'Capão Bonito' },
  { code: '119', value: 'Capela do Alto' },
  { code: '120', value: 'Capivari' },
  { code: '121', value: 'Caraguatatuba' },
  { code: '122', value: 'Carapicuíba' },
  { code: '123', value: 'Cardoso' },
  { code: '124', value: 'Casa Branca' },
  { code: '125', value: 'Cássia dos Coqueiros' },
  { code: '126', value: 'Castilho' },
  { code: '127', value: 'Catanduva' },
  { code: '128', value: 'Catiguá' },
  { code: '129', value: 'Cedral' },
  { code: '130', value: 'Cerqueira César' },
  { code: '131', value: 'Cerquilho' },
  { code: '132', value: 'Cesário Lange' },
  { code: '133', value: 'Charqueada' },
  { code: '134', value: 'Chavantes' },
  { code: '135', value: 'Clementina' },
  { code: '136', value: 'Colina' },
  { code: '137', value: 'Colômbia' },
  { code: '138', value: 'Conchal' },
  { code: '139', value: 'Conchas' },
  { code: '140', value: 'Cordeirópolis' },
  { code: '141', value: 'Coroados' },
  { code: '142', value: 'Coronel Macedo' },
  { code: '143', value: 'Corumbataí' },
  { code: '144', value: 'Cosmópolis' },
  { code: '145', value: 'Cosmorama' },
  { code: '146', value: 'Cotia' },
  { code: '147', value: 'Cravinhos' },
  { code: '148', value: 'Cristais Paulista' },
  { code: '149', value: 'Cruzália' },
  { code: '150', value: 'Cruzeiro' },
  { code: '151', value: 'Cubatão' },
  { code: '152', value: 'Cunha' },
  { code: '153', value: 'Descalvado' },
  { code: '154', value: 'Diadema' },
  { code: '155', value: 'Dirce Reis' },
  { code: '156', value: 'Divinolândia' },
  { code: '157', value: 'Dobrada' },
  { code: '158', value: 'Dois Córregos' },
  { code: '159', value: 'Dolcinópolis' },
  { code: '160', value: 'Dourado' },
  { code: '161', value: 'Dracena' },
  { code: '162', value: 'Duartina' },
  { code: '163', value: 'Dumont' },
  { code: '164', value: 'Echaporã' },
  { code: '165', value: 'Eldorado' },
  { code: '166', value: 'Elias Fausto' },
  { code: '167', value: 'Elisiário' },
  { code: '168', value: 'Embaúba' },
  { code: '169', value: 'Embu' },
  { code: '170', value: 'Embu-Guaçu' },
  { code: '171', value: 'Emilianópolis' },
  { code: '172', value: 'Engenheiro Coelho' },
  { code: '173', value: 'Espírito Santo do Pinhal' },
  { code: '174', value: 'Espírito Santo do Turvo' },
  { code: '175', value: 'Estiva Gerbi' },
  { code: '176', value: "Estrela d'Oeste" },
  { code: '177', value: 'Estrela do Norte' },
  { code: '178', value: 'Euclides da Cunha Paulista' },
  { code: '179', value: 'Fartura' },
  { code: '180', value: 'Fernando Prestes' },
  { code: '181', value: 'Fernandópolis' },
  { code: '182', value: 'Fernão' },
  { code: '183', value: 'Ferraz de Vasconcelos' },
  { code: '184', value: 'Flora Rica' },
  { code: '185', value: 'Floreal' },
  { code: '186', value: 'Florínia' },
  { code: '187', value: 'Flórida Paulista' },
  { code: '188', value: 'Franca' },
  { code: '189', value: 'Francisco Morato' },
  { code: '190', value: 'Franco da Rocha' },
  { code: '191', value: 'Gabriel Monteiro' },
  { code: '192', value: 'Gália' },
  { code: '193', value: 'Garça' },
  { code: '194', value: 'Gastão Vidigal' },
  { code: '195', value: 'Gavião Peixoto' },
  { code: '196', value: 'General Salgado' },
  { code: '197', value: 'Getulina' },
  { code: '198', value: 'Glicério' },
  { code: '199', value: 'Guaiçara' },
  { code: '200', value: 'Guaimbê' },
  { code: '201', value: 'Guaíra' },
  { code: '202', value: 'Guapiaçu' },
  { code: '203', value: 'Guapiara' },
  { code: '204', value: 'Guará' },
  { code: '205', value: 'Guaraçaí' },
  { code: '206', value: 'Guaraci' },
  { code: '207', value: "Guarani d'Oeste" },
  { code: '208', value: 'Guarantã' },
  { code: '209', value: 'Guararapes' },
  { code: '210', value: 'Guararema' },
  { code: '211', value: 'Guaratinguetá' },
  { code: '212', value: 'Guareí' },
  { code: '213', value: 'Guariba' },
  { code: '214', value: 'Guarujá' },
  { code: '215', value: 'Guarulhos' },
  { code: '216', value: 'Guatapará' },
  { code: '217', value: 'Guzolândia' },
  { code: '218', value: 'Herculândia' },
  { code: '219', value: 'Holambra' },
  { code: '220', value: 'Hortolândia' },
  { code: '221', value: 'Iacanga' },
  { code: '222', value: 'Iacri' },
  { code: '223', value: 'Iaras' },
  { code: '224', value: 'Ibaté' },
  { code: '225', value: 'Ibirá' },
  { code: '226', value: 'Ibirarema' },
  { code: '227', value: 'Ibitinga' },
  { code: '228', value: 'Ibiúna' },
  { code: '229', value: 'Icém' },
  { code: '230', value: 'Iepê' },
  { code: '231', value: 'Igaraçu do Tietê' },
  { code: '232', value: 'Igarapava' },
  { code: '233', value: 'Igaratá' },
  { code: '234', value: 'Iguape' },
  { code: '235', value: 'Ilha Comprida' },
  { code: '236', value: 'Ilha Solteira' },
  { code: '237', value: 'Ilhabela' },
  { code: '238', value: 'Indaiatuba' },
  { code: '239', value: 'Indiana' },
  { code: '240', value: 'Indiaporã' },
  { code: '241', value: 'Inúbia Paulista' },
  { code: '242', value: 'Ipauçu' },
  { code: '243', value: 'Iperó' },
  { code: '244', value: 'Ipeúna' },
  { code: '245', value: 'Ipiguá' },
  { code: '246', value: 'Iporanga' },
  { code: '247', value: 'Ipuã' },
  { code: '248', value: 'Iracemápolis' },
  { code: '249', value: 'Irapuã' },
  { code: '250', value: 'Irapuru' },
  { code: '251', value: 'Itaberá' },
  { code: '252', value: 'Itaí' },
  { code: '253', value: 'Itajobi' },
  { code: '254', value: 'Itaju' },
  { code: '255', value: 'Itanhaém' },
  { code: '256', value: 'Itaóca' },
  { code: '257', value: 'Itapecerica da Serra' },
  { code: '258', value: 'Itapetininga' },
  { code: '259', value: 'Itapeva' },
  { code: '260', value: 'Itapevi' },
  { code: '261', value: 'Itapira' },
  { code: '262', value: 'Itapirapuã Paulista' },
  { code: '263', value: 'Itápolis' },
  { code: '264', value: 'Itaporanga' },
  { code: '265', value: 'Itapuí' },
  { code: '266', value: 'Itapura' },
  { code: '267', value: 'Itaquaquecetuba' },
  { code: '268', value: 'Itararé' },
  { code: '269', value: 'Itariri' },
  { code: '270', value: 'Itatiba' },
  { code: '271', value: 'Itatinga' },
  { code: '272', value: 'Itirapina' },
  { code: '273', value: 'Itirapuã' },
  { code: '274', value: 'Itobi' },
  { code: '275', value: 'Itu' },
  { code: '276', value: 'Itupeva' },
  { code: '277', value: 'Ituverava' },
  { code: '278', value: 'Jaborandi' },
  { code: '279', value: 'Jaboticabal' },
  { code: '280', value: 'Jacareí' },
  { code: '281', value: 'Jaci' },
  { code: '282', value: 'Jacupiranga' },
  { code: '283', value: 'Jaguariúna' },
  { code: '284', value: 'Jales' },
  { code: '285', value: 'Jambeiro' },
  { code: '286', value: 'Jandira' },
  { code: '287', value: 'Jardinópolis' },
  { code: '288', value: 'Jarinu' },
  { code: '289', value: 'Jaú' },
  { code: '290', value: 'Jeriquara' },
  { code: '291', value: 'Joanópolis' },
  { code: '292', value: 'João Ramalho' },
  { code: '293', value: 'José Bonifácio' },
  { code: '294', value: 'Júlio Mesquita' },
  { code: '295', value: 'Jumirim' },
  { code: '296', value: 'Jundiaí' },
  { code: '297', value: 'Junqueirópolis' },
  { code: '298', value: 'Juquiá' },
  { code: '299', value: 'Juquitiba' },
  { code: '300', value: 'Lagoinha' },
  { code: '301', value: 'Laranjal Paulista' },
  { code: '302', value: 'Lavínia' },
  { code: '303', value: 'Lavrinhas' },
  { code: '304', value: 'Leme' },
  { code: '305', value: 'Lençóis Paulista' },
  { code: '306', value: 'Limeira' },
  { code: '307', value: 'Lindóia' },
  { code: '308', value: 'Lins' },
  { code: '309', value: 'Lorena' },
  { code: '310', value: 'Lourdes' },
  { code: '311', value: 'Louveira' },
  { code: '312', value: 'Lucélia' },
  { code: '313', value: 'Lucianópolis' },
  { code: '314', value: 'Luís Antônio' },
  { code: '315', value: 'Luiziânia' },
  { code: '316', value: 'Lupércio' },
  { code: '317', value: 'Lutécia' },
  { code: '318', value: 'Macatuba' },
  { code: '319', value: 'Macaubal' },
  { code: '320', value: 'Macedônia' },
  { code: '321', value: 'Magda' },
  { code: '322', value: 'Mairinque' },
  { code: '323', value: 'Mairiporã' },
  { code: '324', value: 'Manduri' },
  { code: '325', value: 'Marabá Paulista' },
  { code: '326', value: 'Maracaí' },
  { code: '327', value: 'Marapoama' },
  { code: '328', value: 'Mariápolis' },
  { code: '329', value: 'Marília' },
  { code: '330', value: 'Marinópolis' },
  { code: '331', value: 'Martinópolis' },
  { code: '332', value: 'Matão' },
  { code: '333', value: 'Mauá' },
  { code: '334', value: 'Mendonça' },
  { code: '335', value: 'Meridiano' },
  { code: '336', value: 'Mesópolis' },
  { code: '337', value: 'Miguelópolis' },
  { code: '338', value: 'Mineiros do Tietê' },
  { code: '339', value: 'Mira Estrela' },
  { code: '340', value: 'Miracatu' },
  { code: '341', value: 'Mirandópolis' },
  { code: '342', value: 'Mirante do Paranapanema' },
  { code: '343', value: 'Mirassol' },
  { code: '344', value: 'Mirassolândia' },
  { code: '345', value: 'Mococa' },
  { code: '346', value: 'Mogi das Cruzes' },
  { code: '347', value: 'Mogi-Guaçu' },
  { code: '348', value: 'Mogi-Mirim' },
  { code: '349', value: 'Mombuca' },
  { code: '350', value: 'Monções' },
  { code: '351', value: 'Mongaguá' },
  { code: '352', value: 'Monte Alegre do Sul' },
  { code: '353', value: 'Monte Alto' },
  { code: '354', value: 'Monte Aprazível' },
  { code: '355', value: 'Monte Azul Paulista' },
  { code: '356', value: 'Monte Castelo' },
  { code: '357', value: 'Monte Mor' },
  { code: '358', value: 'Monteiro Lobato' },
  { code: '359', value: 'Morro Agudo' },
  { code: '360', value: 'Morungaba' },
  { code: '361', value: 'Motuca' },
  { code: '362', value: 'Murutinga do Sul' },
  { code: '363', value: 'Nantes' },
  { code: '364', value: 'Narandiba' },
  { code: '365', value: 'Natividade da Serra' },
  { code: '366', value: 'Nazaré Paulista' },
  { code: '367', value: 'Neves Paulista' },
  { code: '368', value: 'Nhandeara' },
  { code: '369', value: 'Nipoã' },
  { code: '370', value: 'Nova Aliança' },
  { code: '371', value: 'Nova Campina' },
  { code: '372', value: 'Nova Canaã Paulista' },
  { code: '373', value: 'Nova Castilho' },
  { code: '374', value: 'Nova Europa' },
  { code: '375', value: 'Nova Granada' },
  { code: '376', value: 'Nova Guataporanga' },
  { code: '377', value: 'Nova Independência' },
  { code: '378', value: 'Nova Luzitânia' },
  { code: '379', value: 'Nova Odessa' },
  { code: '380', value: 'Novais' },
  { code: '381', value: 'Novo Horizonte' },
  { code: '382', value: 'Nuporanga' },
  { code: '383', value: 'Ocauçu' },
  { code: '384', value: 'Óleo' },
  { code: '385', value: 'Olímpia' },
  { code: '386', value: 'Onda Verde' },
  { code: '387', value: 'Oriente' },
  { code: '388', value: 'Orindiúva' },
  { code: '389', value: 'Orlândia' },
  { code: '390', value: 'Osasco' },
  { code: '391', value: 'Oscar Bressane' },
  { code: '392', value: 'Osvaldo Cruz' },
  { code: '393', value: 'Ourinhos' },
  { code: '394', value: 'Ouro Verde' },
  { code: '395', value: 'Ouroeste' },
  { code: '396', value: 'Pacaembu' },
  { code: '397', value: 'Palestina' },
  { code: '398', value: 'Palmares Paulista' },
  { code: '399', value: "Palmeira d'Oeste" },
  { code: '400', value: 'Palmital' },
  { code: '401', value: 'Panorama' },
  { code: '402', value: 'Paraguaçu Paulista' },
  { code: '403', value: 'Paraibuna' },
  { code: '404', value: 'Paraíso' },
  { code: '405', value: 'Paranapanema' },
  { code: '406', value: 'Paranapuã' },
  { code: '407', value: 'Parapuã' },
  { code: '408', value: 'Pardinho' },
  { code: '409', value: 'Pariquera-Açu' },
  { code: '410', value: 'Parisi' },
  { code: '411', value: 'Patrocínio Paulista' },
  { code: '412', value: 'Paulicéia' },
  { code: '413', value: 'Paulínia' },
  { code: '414', value: 'Paulistânia' },
  { code: '415', value: 'Paulo de Faria' },
  { code: '416', value: 'Pederneiras' },
  { code: '417', value: 'Pedra Bela' },
  { code: '418', value: 'Pedranópolis' },
  { code: '419', value: 'Pedregulho' },
  { code: '420', value: 'Pedreira' },
  { code: '421', value: 'Pedrinhas Paulista' },
  { code: '422', value: 'Pedro de Toledo' },
  { code: '423', value: 'Penápolis' },
  { code: '424', value: 'Pereira Barreto' },
  { code: '425', value: 'Pereiras' },
  { code: '426', value: 'Peruíbe' },
  { code: '427', value: 'Piacatu' },
  { code: '428', value: 'Piedade' },
  { code: '429', value: 'Pilar do Sul' },
  { code: '430', value: 'Pindamonhangaba' },
  { code: '431', value: 'Pindorama' },
  { code: '432', value: 'Pinhalzinho' },
  { code: '433', value: 'Piquerobi' },
  { code: '434', value: 'Piquete' },
  { code: '435', value: 'Piracaia' },
  { code: '436', value: 'Piracicaba' },
  { code: '437', value: 'Piraju' },
  { code: '438', value: 'Pirajuí' },
  { code: '439', value: 'Pirangi' },
  { code: '440', value: 'Pirapora do Bom Jesus' },
  { code: '441', value: 'Pirapozinho' },
  { code: '442', value: 'Pirassununga' },
  { code: '443', value: 'Piratininga' },
  { code: '444', value: 'Pitangueiras' },
  { code: '445', value: 'Planalto' },
  { code: '446', value: 'Platina' },
  { code: '447', value: 'Poá' },
  { code: '448', value: 'Poloni' },
  { code: '449', value: 'Pompéia' },
  { code: '450', value: 'Pongaí' },
  { code: '451', value: 'Pontal' },
  { code: '452', value: 'Pontalinda' },
  { code: '453', value: 'Pontes Gestal' },
  { code: '454', value: 'Populina' },
  { code: '455', value: 'Porangaba' },
  { code: '456', value: 'Porto Feliz' },
  { code: '457', value: 'Porto Ferreira' },
  { code: '458', value: 'Potim' },
  { code: '459', value: 'Potirendaba' },
  { code: '460', value: 'Pracinha' },
  { code: '461', value: 'Pradópolis' },
  { code: '462', value: 'Praia Grande' },
  { code: '463', value: 'Pratânia' },
  { code: '464', value: 'Presidente Alves' },
  { code: '465', value: 'Presidente Bernardes' },
  { code: '466', value: 'Presidente Epitácio' },
  { code: '467', value: 'Presidente Prudente' },
  { code: '468', value: 'Presidente Venceslau' },
  { code: '469', value: 'Promissão' },
  { code: '470', value: 'Quadra' },
  { code: '471', value: 'Quatá' },
  { code: '472', value: 'Queiroz' },
  { code: '473', value: 'Queluz' },
  { code: '474', value: 'Quintana' },
  { code: '475', value: 'Rafard' },
  { code: '476', value: 'Rancharia' },
  { code: '477', value: 'Redenção da Serra' },
  { code: '478', value: 'Regente Feijó' },
  { code: '479', value: 'Reginópolis' },
  { code: '480', value: 'Registro' },
  { code: '481', value: 'Restinga' },
  { code: '482', value: 'Ribeira' },
  { code: '483', value: 'Ribeirão Bonito' },
  { code: '484', value: 'Ribeirão Branco' },
  { code: '485', value: 'Ribeirão Corrente' },
  { code: '486', value: 'Ribeirão do Sul' },
  { code: '487', value: 'Ribeirão dos Índios' },
  { code: '488', value: 'Ribeirão Grande' },
  { code: '489', value: 'Ribeirão Pires' },
  { code: '490', value: 'Ribeirão Preto' },
  { code: '491', value: 'Rifaina' },
  { code: '492', value: 'Rincão' },
  { code: '493', value: 'Rinópolis' },
  { code: '494', value: 'Rio Claro' },
  { code: '495', value: 'Rio das Pedras' },
  { code: '496', value: 'Rio Grande da Serra' },
  { code: '497', value: 'Riolândia' },
  { code: '498', value: 'Riversul' },
  { code: '499', value: 'Rosana' },
  { code: '500', value: 'Roseira' },
  { code: '501', value: 'Rubiácea' },
  { code: '502', value: 'Rubinéia' },
  { code: '503', value: 'Sabino' },
  { code: '504', value: 'Sagres' },
  { code: '505', value: 'Sales' },
  { code: '506', value: 'Sales Oliveira' },
  { code: '507', value: 'Salesópolis' },
  { code: '508', value: 'Salmourão' },
  { code: '509', value: 'Saltinho' },
  { code: '510', value: 'Salto' },
  { code: '511', value: 'Salto de Pirapora' },
  { code: '512', value: 'Salto Grande' },
  { code: '513', value: 'Sandovalina' },
  { code: '514', value: 'Santa Adélia' },
  { code: '515', value: 'Santa Albertina' },
  { code: '516', value: "Santa Bárbara d'Oeste" },
  { code: '517', value: 'Santa Branca' },
  { code: '518', value: "Santa Clara d'Oeste" },
  { code: '519', value: 'Santa Cruz da Conceição' },
  { code: '520', value: 'Santa Cruz da Esperança' },
  { code: '521', value: 'Santa Cruz das Palmeiras' },
  { code: '522', value: 'Santa Cruz do Rio Pardo' },
  { code: '523', value: 'Santa Ernestina' },
  { code: '524', value: 'Santa Fé do Sul' },
  { code: '525', value: 'Santa Gertrudes' },
  { code: '526', value: 'Santa Isabel' },
  { code: '527', value: 'Santa Lúcia' },
  { code: '528', value: 'Santa Maria da Serra' },
  { code: '529', value: 'Santa Mercedes' },
  { code: '530', value: "Santa Rita d'Oeste" },
  { code: '531', value: 'Santa Rita do Passa Quatro' },
  { code: '532', value: 'Santa Rosa de Viterbo' },
  { code: '533', value: 'Santa Salete' },
  { code: '534', value: 'Santana da Ponte Pensa' },
  { code: '535', value: 'Santana de Parnaíba' },
  { code: '536', value: 'Santo Anastácio' },
  { code: '537', value: 'Santo André' },
  { code: '538', value: 'Santo Antônio da Alegria' },
  { code: '539', value: 'Santo Antônio de Posse' },
  { code: '540', value: 'Santo Antônio do Aracanguá' },
  { code: '541', value: 'Santo Antônio do Jardim' },
  { code: '542', value: 'Santo Antônio do Pinhal' },
  { code: '543', value: 'Santo Expedito' },
  { code: '544', value: 'Santópolis do Aguapeí' },
  { code: '545', value: 'Santos' },
  { code: '546', value: 'São Bento do Sapucaí' },
  { code: '547', value: 'São Bernardo do Campo' },
  { code: '548', value: 'São Caetano do Sul' },
  { code: '549', value: 'São Carlos' },
  { code: '550', value: 'São Francisco' },
  { code: '551', value: 'São João da Boa Vista' },
  { code: '552', value: 'São João das Duas Pontes' },
  { code: '553', value: 'São João de Iracema' },
  { code: '554', value: "São João do Pau d'Alho" },
  { code: '555', value: 'São Joaquim da Barra' },
  { code: '556', value: 'São José da Bela Vista' },
  { code: '557', value: 'São José do Barreiro' },
  { code: '558', value: 'São José do Rio Pardo' },
  { code: '559', value: 'São José do Rio Preto' },
  { code: '560', value: 'São José dos Campos' },
  { code: '561', value: 'São Lourenço da Serra' },
  { code: '562', value: 'São Luís do Paraitinga' },
  { code: '563', value: 'São Manuel' },
  { code: '564', value: 'São Miguel Arcanjo' },
  { code: '565', value: 'São Paulo' },
  { code: '566', value: 'São Pedro' },
  { code: '567', value: 'São Pedro do Turvo' },
  { code: '568', value: 'São Roque' },
  { code: '569', value: 'São Sebastião' },
  { code: '570', value: 'São Sebastião da Grama' },
  { code: '571', value: 'São Simão' },
  { code: '572', value: 'São Vicente' },
  { code: '573', value: 'Sarapuí' },
  { code: '574', value: 'Sarutaiá' },
  { code: '575', value: 'Sebastianópolis do Sul' },
  { code: '576', value: 'Serra Azul' },
  { code: '577', value: 'Serra Negra' },
  { code: '578', value: 'Serrana' },
  { code: '579', value: 'Sertãozinho' },
  { code: '580', value: 'Sete Barras' },
  { code: '581', value: 'Severínia' },
  { code: '582', value: 'Silveiras' },
  { code: '583', value: 'Socorro' },
  { code: '584', value: 'Sorocaba' },
  { code: '585', value: 'Sud Mennucci' },
  { code: '586', value: 'Sumaré' },
  { code: '587', value: 'Suzanápolis' },
  { code: '588', value: 'Suzano' },
  { code: '589', value: 'Tabapuã' },
  { code: '590', value: 'Tabatinga' },
  { code: '591', value: 'Taboão da Serra' },
  { code: '592', value: 'Taciba' },
  { code: '593', value: 'Taguaí' },
  { code: '594', value: 'Taiaçu' },
  { code: '595', value: 'Taiúva' },
  { code: '596', value: 'Tambaú' },
  { code: '597', value: 'Tanabi' },
  { code: '598', value: 'Tapiraí' },
  { code: '599', value: 'Tapiratiba' },
  { code: '600', value: 'Taquaral' },
  { code: '601', value: 'Taquaritinga' },
  { code: '602', value: 'Taquarituba' },
  { code: '603', value: 'Taquarivaí' },
  { code: '604', value: 'Tarabai' },
  { code: '605', value: 'Tarumã' },
  { code: '606', value: 'Tatuí' },
  { code: '607', value: 'Taubaté' },
  { code: '608', value: 'Tejupá' },
  { code: '609', value: 'Teodoro Sampaio' },
  { code: '610', value: 'Terra Roxa' },
  { code: '611', value: 'Tietê' },
  { code: '612', value: 'Timburi' },
  { code: '613', value: 'Torre de Pedra' },
  { code: '614', value: 'Torrinha' },
  { code: '615', value: 'Trabiju' },
  { code: '616', value: 'Tremembé' },
  { code: '617', value: 'Três Fronteiras' },
  { code: '618', value: 'Tuiuti' },
  { code: '619', value: 'Tupã' },
  { code: '620', value: 'Tupi Paulista' },
  { code: '621', value: 'Turiúba' },
  { code: '622', value: 'Turmalina' },
  { code: '623', value: 'Ubarana' },
  { code: '624', value: 'Ubatuba' },
  { code: '625', value: 'Ubirajara' },
  { code: '626', value: 'Uchoa' },
  { code: '627', value: 'União Paulista' },
  { code: '628', value: 'Urânia' },
  { code: '629', value: 'Uru' },
  { code: '630', value: 'Urupês' },
  { code: '631', value: 'Valentim Gentil' },
  { code: '632', value: 'Valinhos' },
  { code: '633', value: 'Valparaíso' },
  { code: '634', value: 'Vargem' },
  { code: '635', value: 'Vargem Grande do Sul' },
  { code: '636', value: 'Vargem Grande Paulista' },
  { code: '637', value: 'Várzea Paulista' },
  { code: '638', value: 'Vera Cruz' },
  { code: '639', value: 'Vinhedo' },
  { code: '640', value: 'Viradouro' },
  { code: '641', value: 'Vista Alegre do Alto' },
  { code: '642', value: 'Vitória Brasil' },
  { code: '643', value: 'Votorantim' },
  { code: '644', value: 'Votuporanga' },
  { code: '645', value: 'Zacarias' },
];
